Implement viem Client
PureStake/xcm-sdk pull request #131
Opened 2023-09-05 08:06 UTC by mmaurello

### Description

Please explain the changes this PR addresses here.

### Checklist

- [ ] If this requires a documentation change, I have created a PR in [moonbeam-docs](https://github.com/PureStake/moonbeam-docs) repository.
- [ ] If this requires it, I have updated the Readme
- [ ] If necessary, I have updated the examples
- [ ] I have verified if I need to create/update unit tests
- [ ] I have verified if I need to create/update acceptance tests
- [ ] If necessary, I have run acceptance tests on this branch in CI

2023-09-06 13:30 UTC, ekenigs requested changes
Please check my comments.

2023-09-06 13:30 UTC, ekenigs commented on packages/sdk/src/contract/contracts/Xtokens/Xtokens.ts
> +    this.#client = isEthersSigner(signer)
To simplify stuff I would try to use [getContract](https://viem.sh/docs/contract/getContract.html).

2023-09-06 13:30 UTC, ekenigs commented on packages/sdk/src/sdk.interfaces.ts
> +  ethersSigner?: EthersSigner;
```suggestion
  /**
   * @deprecated ethersSigner - is deprecated and will be removed in v2, use evmSigner instead
   */
  ethersSigner?: EthersSigner;
```

2023-09-07 12:02 UTC, mmaurello commented on packages/sdk/package.json
> +    "viem": "^1.10.3"
left them as `peerDependencies`

2023-09-11 08:51 UTC, merged