Local assets
PureStake/xcm-sdk pull request #31
Opened 2022-10-11 10:28 UTC by fxgamundi

2022-10-14 09:42 UTC, ekenigs requested changes
I also tried to deposit xusdc with our dapp and it didn't work. Not sure what could be wrong.

2022-10-15 01:10 UTC, fxgamundi commented
> I also tried to deposit xusdc with our dapp and it didn't work. Not sure what could be wrong.

Centrifuge still haven't enabled the TransferMultiCurrencies extrinsic in their chain, so there's no way to actually test USDC right now

2022-10-17 07:56 UTC, ekenigs requested changes
Looks good besides the flag. Please check create a PR to docs because interface change.

2022-10-17 07:56 UTC, ekenigs commented on packages/sdk/src/sdk/sdk.deposit.ts
> +      isDifferentAsset: xcmFeeAssetConfig.asset.id !== asset.id,
I'm not a big fan of this flag. I would not add it.

2022-10-19 17:04 UTC, fxgamundi commented
[Moonbeam docs PR](https://github.com/PureStake/moonbeam-docs/pull/441)

2022-10-19 17:09 UTC, ekenigs approved these changes

2022-10-20 11:02 UTC, fxgamundi commented
Updated to latest PolkadotJS deps and tested every deposit against live version. All good

2022-10-20 11:18 UTC, ekenigs approved these changes

2022-10-20 11:20 UTC, merged