v1 fixes
PureStake/xcm-sdk pull request #88
Opened 2023-06-07 08:10 UTC by ekenigs

2023-06-09 20:18 UTC, mmaurello commented on packages/config/src/configs/moonbeam.ts
> +        amount: 0.05,
Technically the fee is lower and the existential deposit (what we consider `minBalance`) is the one that makes it go high to .05 
![image](https://github.com/PureStake/xcm-sdk/assets/93129175/41b1b6a6-62cb-4d62-aff3-e505c3641989)
We would have to create another function in the `AssetMinBuilder` file
However seeing that it is not that significant and our current work load we could leave it like this

2023-06-13 14:37 UTC, mmaurello requested changes
We are missing minimal balance for ausd in acala and in karura, it should be `assetMetadatas()`
![image](https://github.com/PureStake/xcm-sdk/assets/93129175/9a8d9869-129f-4992-ae2a-87f0ef9a0b6e)

2023-06-14 06:47 UTC, ekenigs commented
> We are missing minimal balance for ausd in acala and in karura, it should be `assetMetadatas()` ![image](https://user-images.githubusercontent.com/93129175/245512187-9a8d9869-129f-4992-ae2a-87f0ef9a0b6e.png)

I did a fix

2023-06-14 10:16 UTC, mmaurello approved these changes

2023-06-14 10:19 UTC, merged